[workspace]
members = ["exercises/*/*", "helpers/common", "helpers/mdbook-exercise-linker", "helpers/ticket_fields", "sandbox"]
resolver = "2"

[profile.dev]
overflow-checks = false     # Disable integer overflow checks.
